name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: riboney/js-discordbot-for-learning/js-discord-bot
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: prod.Dockerfile
          tags: latest

      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
            GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}
            COMMAND_PREFIX: ${{ secrets.DISCORD_BOT_PREFIX }}
            OWNER: ${{ secrets.DISCORD_BOT_OWNER }}
            ACTIVITY_NAME: ${{ secrets.ACTIVITY_NAME }}
            ACTIVITY_TYPE: ${{ secrets.ACTIVITY_TYPE }}
            NODE_ENV: $${{ secrets.NODE_ENV }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, BOT_TOKEN, COMMAND_PREFIX, OWNER, ACTIVITY_NAME, ACTIVITY_TYPE, NODE_ENV
          script: |
            BOT_TOKEN=$BOT_TOKEN COMMAND_PREFIX=$COMMAND_PREFIX OWNER=$OWNER ACTIVITY_NAME=$ACTIVITY_NAME ACTIVITY_TYPE=$ACTIVITY_TYPE NODE_ENV=$NODE_ENV
            docker stop $(docker ps -a -q)
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/riboney/js-discordbot-for-learning/js-discord-bot:latest
            docker container run -e BOT_TOKEN=$BOT_TOKEN -e COMMAND_PREFIX=$COMMAND_PREFIX -e OWNER=$OWNER \n
            -e ACTIVITY_NAME=$ACTIVITY_NAME -e ACTIVITY_TYPE=$ACTIVITY_TYPE -e NODE_ENV=$NODE_ENV \n
            -dit docker.pkg.github.com/riboney/js-discordbot-for-learning/js-discord-bot:latest
