# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v2

    - name: Create .env file
    - uses: SpicyPizza/create-envfile@v1.1
      with:
        # The filename for the envfile
        file_name: dev.env
        # The directory to put the envfile in
        directory: env/
        envKey_BOT_TOKEN: DISCORD_TOKEN
        envKey_COMMAND_PREFIX: DISCORD_BOT_PREFIX
        envKey_OWNER: DISCORD_BOT_OWNER

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm test
